language: php

php:
  - hhvm
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

services:
  - memcached # will start memcached

before_install:
  - composer self-update

before_script:
  - composer update --dev
  - phpenv rehash

script:
  - phpunit --configuration phpunit.travis.xml
